import React, { useEffect, useState } from 'react';

const FRAME_DURATION = 10 * 30; // 10 seconds at 30fps

export const ConfigStructureOverview: React.FC = () => {
  const [frame, setFrame] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setFrame(f => (f + 1) % FRAME_DURATION);
    }, 1000 / 30);
    return () => clearInterval(interval);
  }, []);

  const cycleFrame = frame % FRAME_DURATION;

  const colors = {
    background: '#F8FAFC',
    text: '#1E293B',
    textMuted: '#64748B',
    listColor: '#3B82F6',
    hashColor: '#8B5CF6',
    zsetColor: '#F59E0B',
    cardBg: '#fff',
    border: '#E2E8F0',
  };

  const getAnimationProgress = (start: number, duration: number) => {
    return Math.min(1, Math.max(0, (cycleFrame - start) / duration));
  };

  // Configuration categories
  const configCategories = [
    {
      title: 'List 配置',
      color: colors.listColor,
      configs: [
        { name: 'list-max-ziplist-size', default: '-2', unit: 'bytes', desc: 'ziplist最大字节数' },
        { name: 'list-compress-depth', default: '0', unit: 'nodes', desc: '压缩深度' },
      ],
    },
    {
      title: 'Hash 配置',
      color: colors.hashColor,
      configs: [
        { name: 'hash-max-ziplist-entries', default: '512', unit: 'entries', desc: '最大条目数' },
        { name: 'hash-max-ziplist-value', default: '64', unit: 'bytes', desc: '最大value字节数' },
      ],
    },
    {
      title: 'Sorted Set 配置',
      color: colors.zsetColor,
      configs: [
        { name: 'zset-max-ziplist-entries', default: '128', unit: 'entries', desc: '最大条目数' },
        { name: 'zset-max-ziplist-value', default: '64', unit: 'bytes', desc: '最大value字节数' },
      ],
    },
  ];

  // Redis.conf sections
  const sections = [
    { name: 'MEMORY MANAGEMENT', line: '~line 42' },
    { name: 'ACTIVE DEFRAGMENTATION', line: '~line 218' },
    { name: 'APPEND ONLY MODE', line: '~line 899' },
  ];

  return (
    <div style={{
      backgroundColor: colors.background,
      fontFamily: 'Inter, system-ui, sans-serif',
      width: '100%',
      height: '100%',
      position: 'relative',
      overflow: 'hidden',
    }}>
      {/* Title */}
      <div style={{
        position: 'absolute',
        top: 25,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: colors.text,
        fontSize: 38,
        fontWeight: 700,
      }}>
        Redis.conf 配置参数位置
      </div>

      {/* Left side - Redis.conf structure */}
      <div style={{
        position: 'absolute',
        top: 100,
        left: 40,
        width: 280,
      }}>
        <div style={{
          color: colors.text,
          fontSize: 20,
          fontWeight: 600,
          marginBottom: 16,
        }}>
          Redis.conf 结构
        </div>

        {/* File representation */}
        <div style={{
          backgroundColor: colors.cardBg,
          border: `1px solid ${colors.border}`,
          borderRadius: 12,
          padding: 16,
          fontFamily: 'JetBrains Mono, Consolas, monospace',
          fontSize: 13,
        }}>
          <div style={{ color: colors.textMuted, marginBottom: 8 }}># Redis Configuration</div>
          <div style={{ color: colors.textMuted, marginBottom: 8 }}># Generated by...</div>
          <div style={{ height: 8 }} />

          {/* Sections */}
          {sections.map((section, idx) => {
            const isHighlighted = cycleFrame >= idx * 50 + 20 && cycleFrame < idx * 50 + 70;
            return (
              <div key={section.name} style={{
                marginBottom: 8,
                padding: '4px 8px',
                borderRadius: 4,
                backgroundColor: isHighlighted ? '#F0F9FF' : 'transparent',
                border: isHighlighted ? '1px solid #BAE6FD' : '1px solid transparent',
              }}>
                <div style={{
                  color: isHighlighted ? colors.listColor : colors.textMuted,
                  fontWeight: isHighlighted ? 600 : 400,
                }}>
                  {section.name}
                </div>
                <div style={{ color: colors.textMuted, fontSize: 11 }}>
                  {section.line}
                </div>
              </div>
            );
          })}

          <div style={{ height: 8 }} />
          <div style={{ color: colors.textMuted }}>...</div>
        </div>
      </div>

      {/* Right side - Configuration cards */}
      <div style={{
        position: 'absolute',
        top: 90,
        left: 360,
        right: 40,
      }}>
        <div style={{
          color: colors.text,
          fontSize: 20,
          fontWeight: 600,
          marginBottom: 16,
        }}>
          分类配置参数
        </div>

        {configCategories.map((category, catIdx) => {
          const catProgress = getAnimationProgress(catIdx * 60, 40);

          return (
            <div key={category.title} style={{
              marginBottom: 20,
              opacity: catProgress,
              transform: `translateX(${(1 - catProgress) * 50}px)`,
            }}>
              {/* Category header */}
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: 12,
                marginBottom: 10,
              }}>
                <div style={{
                  width: 16,
                  height: 16,
                  backgroundColor: category.color,
                  borderRadius: 4,
                }} />
                <span style={{
                  color: colors.text,
                  fontSize: 18,
                  fontWeight: 600,
                }}>
                  {category.title}
                </span>
              </div>

              {/* Config cards */}
              <div style={{ display: 'flex', gap: 12 }}>
                {category.configs.map((config, configIdx) => {
                  const configProgress = getAnimationProgress(
                    catIdx * 60 + configIdx * 20 + 20,
                    30
                  );

                  return (
                    <div key={config.name} style={{
                      flex: 1,
                      backgroundColor: colors.cardBg,
                      border: `1px solid ${colors.border}`,
                      borderRadius: 10,
                      padding: 16,
                      opacity: configProgress,
                      transform: `scale(${0.95 + configProgress * 0.05})`,
                    }}>
                      <div style={{
                        fontFamily: 'JetBrains Mono, Consolas, monospace',
                        fontSize: 14,
                        fontWeight: 600,
                        color: category.color,
                        marginBottom: 8,
                      }}>
                        {config.name}
                      </div>
                      <div style={{
                        display: 'flex',
                        alignItems: 'baseline',
                        gap: 6,
                        marginBottom: 4,
                      }}>
                        <span style={{ fontSize: 28, fontWeight: 700, color: colors.text }}>
                          {config.default}
                        </span>
                        <span style={{ fontSize: 14, color: colors.textMuted }}>
                          {config.unit}
                        </span>
                      </div>
                      <div style={{ fontSize: 13, color: colors.textMuted }}>
                        {config.desc}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>

      {/* Bottom indicator */}
      <div style={{
        position: 'absolute',
        bottom: 20,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: colors.textMuted,
        fontSize: 12,
      }}>
        {Math.floor((cycleFrame / FRAME_DURATION) * 10)}s / 10s
      </div>
    </div>
  );
};
